### ISSUE TITLE
NPE during simple filter parsing

### ISSUE THREAD

**Issue by ribrewguy** [vineey/archelix-rsql#26]
I haven't dug into the issue, but when parsing a simple filter `principal == 035489f4-d602-46c5-b568-39d1f852b565` I get an NPE:

```
Caused by: java.lang.NullPointerException
	at com.github.vineey.rql.querydsl.filter.QuerydslRsqlVisitor.visit(QuerydslRsqlVisitor.java:80) ~[rsql-querydsl-filter-2.0.0.RELEASE.jar:?]
	at com.github.vineey.rql.querydsl.filter.QuerydslRsqlVisitor.visit(QuerydslRsqlVisitor.java:37) ~[rsql-querydsl-filter-2.0.0.RELEASE.jar:?]
	at cz.jirutka.rsql.parser.ast.ComparisonNode.accept(ComparisonNode.java:70) ~[rsql-parser-2.1.0.jar:2.1.0]
	at com.github.vineey.rql.querydsl.filter.QuerydslFilterBuilder.visit(QuerydslFilterBuilder.java:34) ~[rsql-querydsl-filter-2.0.0.RELEASE.jar:?]
	at com.github.vineey.rql.querydsl.filter.QuerydslFilterBuilder.visit(QuerydslFilterBuilder.java:31) ~[rsql-querydsl-filter-2.0.0.RELEASE.jar:?]
	at com.github.vineey.rql.filter.parser.DefaultFilterParser.parse(DefaultFilterParser.java:42) ~[rsql-api-filter-2.0.0.RELEASE.jar:?]
```

**Comment by bobonaut** [comment]
@redijedi I see that you use UUID's for the value. The NPE is thrown by the visitor because the "ComparablePath" which is generated for the UUID is seemingly not supported in the library.

Our workaround was to add `@QueryType(PropertyType.SIMPLE)` on the propertie in the entity to let QueryDsl handle the UUID as a String. This lets the Context of the rsql context use the StringPath and everything works proper.
